### ISSUE TITLE
Support for mapping user after a Bind request

### ISSUE THREAD

**Issue by xunleii** [jimlambrt/gldap#35]
**Is your feature request related to a problem? Please describe.**
I am creating an LDAP server using `gldap` and I can't figure out how to ensure that a user performing a search operation has been successfully authenticated just before. 

**Describe the solution you'd like**
It might be helpful to provide at least the connection ID on each message to know "who" (i.e. which connection) made the request.

**Describe alternatives you've considered**
I tried to use any accessible information on the request message to bypass that, but couldn't find anything that would help.

**Comment by jimlambrt** [comment]
Ty for opening this issue!  It should be fairly simple to implement.  Look for a PR later today.

**Comment by xunleii** [comment]
Hi @jimlambrt, that was very quick! Thank you very much for your PR, it was what I was waiting for.

**Comment by pyxistools** [comment]
@jimlambrt , I saw your [example](https://github.com/jimlambrt/gldap/blob/main/examples/simple/main.go#L67) where you use map `authenticatedConnections` in `bindHandler()` to track authenticated users and use `Request.ConnectionID()` in `searchHandler()` to check if the client is authenticated. But you don't clean up this map on unbind or client disconnect. Does the library provide a way to handle client disconnect event? Without it, the map can't be cleaned properly.

**Comment by pyxistools** [comment]
Answering my question: There is a server option `gldap.WithOnClose()` for setting client disconnect handler. The handler receives one argument - closed connection ID. It would be nice to have this in the example for completeness.

**Comment by jimlambrt** [comment]
Opened https://github.com/jimlambrt/gldap/issues/70 which adds gldap.OnClose func to example.
