### ISSUE TITLE
Support for attach and fetch custom data with connection

### ISSUE THREAD

**Issue by xitianfz** [jimlambrt/gldap#37]
**Is your feature request related to a problem? Please describe.**
Currently, in order to maintain connection session data, we can use Request.GetConnectionID() to build an extra session table. Normally the session will be cleared when an unbind request is received. But when the connection is closed without receiving an unbind request, the related session cannot be correctly cleared.

**Describe the solution you'd like**
Provide methods to attach and fetch custom data with each connection:

```go
type conn struct {
        ...
	extra interface{}
}

func (r *Request) SetConnectionExtra(value interface{}) {
	r.conn.extra = value
}
func (r *Request) GetConnectionExtra() interface{} {
	return r.conn.extra
}
```

**Comment by jimlambrt** [comment]
🤔 I wonder if it might be better to add an optional `OnClose(connectionID string)` callback.  This would allow devs to provide whatever clean up function they need which is called whenever a connection is closed.

**Comment by jimlambrt** [comment]
@xitianfz do you think my suggestion above (callback) would work well for your use-case/workflow?

**Comment by xitianfz** [comment]
> @xitianfz do you think my suggestion above (callback) would work well for your use-case/workflow?

😀That's a good idea
