### ISSUE TITLE
TLS Version check for every request

### ISSUE THREAD

**Issue by rohithkumar7582** [jimlambrt/gldap#47]
Hi Jim,
i am working on a project to create an ldap server. i am using your modules to run a startTLS handshake on port 389. i want my server to run on a particular version. conn variable is private hence the TLS version is not reachable to be checked.

request.go:
`type Request struct {
	// ID is the request number for a specific connection.  Every connection has
	// its own request counter which starts at 1.
	ID int
        TLSVersion int
	// conn is needed this for cancellation among other things.
	conn         *conn
	message      Message
	routeOp      routeOperation
	extendedName ExtendedOperationName
}`

a new variable is added - TLSVersion : a public data member
use case: from the request sent by the client, if the server wants to support a particular version say only TLS1.1, we can check the version by doing a r.TLSVersion which sends an integer value ranging from 769 - 772 based on TLS protocol version. This helps the server to lock a particular version and unnecessary requests could be ignored.

it will be great if the code is looped into any of the existing branches.

Thanks, 
Rohith

**Comment by jimlambrt** [comment]
Hi Rohith,

I'm happy to consider adding some sort of way to get a connection's TLS version.  

With that said, in your particular use case could you just specify a `MinVersion` and/or `MaxVersion` (see: [tls.Config](https://pkg.go.dev/crypto/tls#Config) ) when starting TLS?

**Comment by rohithkumar7582** [comment]
Thanks for the input Jim, you are absolutely right, from the client end we do not get to set the tls version and the user might not know it. 

From the server end we lock min version as 1.2 and max as 1.2 so that the client needs to pass trigger 1.2 requests.
We need to support them with appropriate logs before they bind a request. 
// Set up TLS config with server certificate and key
		tlsConfig := &tls.Config{
			Certificates: []tls.Certificate{serverCert},
			ClientCAs: x509.NewCertPool(),
			ClientAuth:   tls.RequireAndVerifyClientCert,
			MinVersion: tls.VersionTLS12,
			MaxVersion: tls.VersionTLS12,
		}
		
The logs received are: 
```
2023/09/04 01:33:31.199877 operations.go:25: StartTLS Handshake error gldap.(Message).StartTLS: handshake error: tls: client offered only unsupported versions: [304]
```
304 will be hard to debug for the client on what that version means.
However, during startTLS Handler call ,only 1.2 will be approved by providing appropriate logs.
v1.3 has a special use case which will be added later.

Hence, before the bind, we check the version as well.

**Comment by rohithkumar7582** [comment]
Hi Jim,

I have used the same log to decode the original tls version and print the logs accordingly. Now it is working fine. Used a regex to retrieve org version from the hexadecimal version and updated the same in the logs. Thank you for your inputs.

Thanks,
Rohith
